# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
        
          # Common Dependencies
          - cd Common
          - mvn dependency:copy-dependencies
          
          # Common Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # GraphPersist Dependencies
          - cd ../GraphPersist
          - mvn dependency:copy-dependencies
          
          # GraphPersist Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # TreeView Dependencies
          - cd ../TreeView
          - mvn dependency:copy-dependencies
          
          # TreeView Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # MatrixView Dependencies
          - cd ../MatrixView
          - mvn dependency:copy-dependencies
          
          # MatrixView Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # FlowTree Dependencies
          # - cd ../FlowTree
          # - mvn dependency:copy-dependencies
          
          # FlowTree Compile
          # - mkdir target/classes
          # - cd src
          # - find -name "*.java" > sources.txt
          # - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          # - cd ../
          # - mvn install
          
          
          # Rings Dependencies
          - cd ../Rings
          - mvn dependency:copy-dependencies
          
          # Rings Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # PhotonField
          - cd ../PhotonField
          - mvn install
          
          
          # ArtifactDetector Dependencies
          - cd ../FlowTree
          - mvn dependency:copy-dependencies
          
          # ArtifactDetector Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          
          # Explorer
          - cd ../Explorer
          - mvn install
          
          # Replicator
          - cd ../Replicator
          - mvn install
          
          # FeedGrowth
          - cd ../FeedGrowth
          - mvn install