# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mvn --version
    - step:
            script:
              - cd Common
              - mvn --version
              - mvn clean install
    - step:
            script:
              - cd GraphPersist
              - mvn clean install
    - step:
            script:
              - cd TreeView
              - mvn clean install
    - step:
            script:
              - cd MatrixView
              - mvn clean install
    - step:
            script:
              - cd FlowTree
              - mvn clean install
    - step:
            script:
              - cd Rings
              - mvn clean install
    - step:
            script:
              - cd PhotonField
              - mvn clean install
    - step:
            script:
              - cd Explorer
              - mvn clean install
    - step:
            script:
              - cd Replicator
              - mvn clean install
      - step:
              script:
                - cd FeedGrowth
                - mvn clean install