# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
          
          # Dead Simple Maven Proxy
          # - export DSMP_HOME=./dsmp
          # - java -classpath ${DSMP_HOME}:${DSMP_HOME}/dsmp-1.1-jar-with-dependencies.jar de.pdark.dsmp.Main ${DSMP_HOME}
          
          - cat /usr/share/maven/settings.xml
          
          # Start our internal maven repo
          - ./apache-archiva-2.2.3/bin/archiva start
          
          # Wait for archiva to start
          - sleep 120
          
          # FlowTree Dependencies
          - mvn dependency:copy-dependencies
          
          # FlowTree Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install
          
          - ls target
          
          # Deploy to downloads
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/output.jar"