# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
          
          # Dead Simple Maven Proxy
          # - export DSMP_HOME=./dsmp
          # - java -classpath ${DSMP_HOME}:${DSMP_HOME}/dsmp-1.1-jar-with-dependencies.jar de.pdark.dsmp.Main ${DSMP_HOME}
          
          - rm /usr/share/maven/conf/settings.xml
          - cp ./settings.xml /usr/share/maven/conf/settings.xml
          
          # Start our internal maven repo
          - ./apache-archiva-2.2.3/bin/archiva start
          
          # Wait for archiva to start
          - sleep 120
          
          # FlowTree Dependencies
          - mvn dependency:copy-dependencies
          
          # Install FlowTree
          - mvn install
          
          # Deploy to downloads
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/FlowTree-0.1-rc.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/TreeView-0.1-rc.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/hsqldb-2.3.4.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/jsch-0.1.53.jar"