# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          - mvn --version
          - cd Common
          - mvn clean install
          - cd ../GraphPersist
          - mvn clean install
          - cd ../TreeView
          - mvn clean install
          - cd ../MatrixView
          - mvn clean install
          - cd ../FlowTree
          - mvn clean install
          - cd ../Rings
          - mvn clean install
          - cd ../PhotonField
          - mvn clean install
          - cd ../Explorer
          - mvn clean install
          - cd ../Replicator
          - mvn clean install
          - cd ../FeedGrowth
          - mvn clean install