# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          # Maven details
          - mvn --version
          # - rm /usr/share/maven/conf/settings.xml
          # - cp ./settings.xml /usr/share/maven/conf/settings.xml

          # FlowTree Dependencies
          # - mvn dependency:copy-dependencies
          
          # Install FlowTree
          - mvn -X -B -s settings.xml install

          # Deploy to repository
          - mvn -B deploy

          # Deploy to downloads
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/FlowTree-0.1-rc.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/TreeView-0.1-rc.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/hsqldb-2.3.4.jar"
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/dependency/jsch-0.1.53.jar"

          # Install docker
          # - sudo apt-get install -y docker

          # Build docker image
          # - docker build . -t almostrealism/parallelize
          # - docker login --username=ashesfall --password=vorlon421
          # - docker push almostrealism/parallelize