# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
          
          # FlowTree Dependencies
          - cd ../FlowTree
          - mvn dependency:copy-dependencies
          
          # FlowTree Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn install