# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Common Dependencies
          - mvn --version
          - cd Common
          - mvn dependency:copy-dependencies
          
          # Common Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn clean install
          
          
          # GraphPersist Dependencies
          - mvn --version
          - cd ../GraphPersist
          - mvn dependency:copy-dependencies
          
          # GraphPersist Compile
          - mkdir target/classes
          - cd src
          - find -name "*.java" > sources.txt
          - javac -cp "../target/dependency/*" -d ../target/classes @sources.txt
          - cd ../
          - mvn clean install
          
          
          # TreeView
          - cd ../TreeView
          - mvn clean install
          
          # MatrixView
          - cd ../MatrixView
          - mvn clean install
          
          # FlowTree
          - cd ../FlowTree
          - mvn clean install
          
          # Rings
          - cd ../Rings
          - mvn clean install
          
          # PhotonField
          - cd ../PhotonField
          - mvn clean install
          
          # Explorer
          - cd ../Explorer
          - mvn clean install
          
          # Replicator
          - cd ../Replicator
          - mvn clean install
          
          # FeedGrowth
          - cd ../FeedGrowth
          - mvn clean install